### ISSUE TITLE
Evaluating the results

### ISSUE THREAD

**Issue by Leonard907** [tau-nlp/scrolls#1]
I have trained a baseline model and run prediction on validation split according to the instructions in the baseline README. However, the command line output didn't seem to give me a destination folder that contains the generated predictions after running through the validation dataset. I was hoping to find a JSON file containing the validation split predictions so that I can use that in the evaluator. Is there a way that I can find the validation split predictions?

Moreover, is there a way for me to evaluate the results on the test split? I see the README in the evaluator folder which has options
[Evaluate predictions for a single dataset (validation only)](https://github.com/tau-nlp/scrolls/blob/main/evaluator/EVALUATE_DATASET.md)
[Evaluate predictions for the entire benchmark (validation only)](https://github.com/tau-nlp/scrolls/blob/main/evaluator/EVALUATE_BENCHMARK.md)
[Prepare Submission File](https://github.com/tau-nlp/scrolls/blob/main/evaluator/PREPARE_SUBMISSION_FILE.md)
[Verify Submission File](https://github.com/tau-nlp/scrolls/blob/main/evaluator/VERIFY_SUBMISSION_FILE.md)  
I want to evaluate the metrics on the test dataset (to see if the resulting numbers match the paper), but I don't want to generate a submission file since I'm just running the baseline models. Is there a way to do that? Thank you very much!

---

EDIT:  I'm currently only running the QMSUM dataset, not the others.

**Comment by UriSha** [comment]
Hi Leonard!

Once you run the prediction command specifed [here](https://github.com/tau-nlp/scrolls/tree/main/baselines#predict), your generations will be in `output_prediction_file = os.path.join(training_args.output_dir, "generated_predictions.json")` - this line is [here](https://github.com/tau-nlp/scrolls/blob/main/baselines/src/run.py#L682).
Thanks for your comment, I just added a relevant log.

Regarding your second question, we keep the SCROLLS test set outputs private. 
If you want to get the test results you can make a private submission to the [leaderboard](https://www.scrolls-benchmark.com/leaderboard) (by checking the "Private submission" checkbox), this way the results will be sent to you via email and won't be published.
You can create a submission file in the format specifed in [this](https://www.scrolls-benchmark.com/getting-started) page, and since you only care about the results of QMSum, you can use your QMSum generations, and mock generations (e.g "hello world") for the rest of the datasets.
Before you make a submission, I recommend verifiyng your submission file is valid using the steps in [Verify Submission File](https://github.com/tau-nlp/scrolls/blob/main/evaluator/VERIFY_SUBMISSION_FILE.md).

**Comment by Leonard907** [comment]
Thanks for the quick reply! I see that the outputs can indeed be written to `generated_predictions.json` so my first question is resolved.  

For the second question, what kind of mocking generations are needed to pass through the verification stage? I tried using the mock pair `example_id1: prediction1` but it didn't seem to work. Does it mean that I should include all the IDs in each of the dataset and use a mock prediction for each ID? Thank you very much!

**Comment by UriSha** [comment]
Yes, you need to iterate over the test sets and output a prediction for every id.

**Comment by Leonard907** [comment]
Got it. Thank you very much!
